/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.principal;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author abner
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form principalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSPEditor = new javax.swing.JScrollPane();
        jTAEditor = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSPErrores = new javax.swing.JScrollPane();
        jTReporte = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMINuevo = new javax.swing.JMenuItem();
        jMIAbrir = new javax.swing.JMenuItem();
        jMIGuardar = new javax.swing.JMenuItem();
        jMIGuardarComo = new javax.swing.JMenuItem();
        jMOpciones = new javax.swing.JMenu();
        jMIAnalizar = new javax.swing.JMenuItem();
        jMIGraficos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parser-py editor");

        jTAEditor.setColumns(20);
        jTAEditor.setRows(5);
        jSPEditor.setViewportView(jTAEditor);

        jTReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jSPErrores.setViewportView(jTReporte);

        jMArchivo.setText("Archivo");

        jMINuevo.setText("Nuevo");
        jMArchivo.add(jMINuevo);

        jMIAbrir.setText("Abrir");
        jMArchivo.add(jMIAbrir);

        jMIGuardar.setText("Guardar");
        jMArchivo.add(jMIGuardar);

        jMIGuardarComo.setText("Guardar como");
        jMArchivo.add(jMIGuardarComo);

        jMenuBar1.add(jMArchivo);

        jMOpciones.setText("Opciones");

        jMIAnalizar.setText("Analizar");
        jMOpciones.add(jMIAnalizar);

        jMIGraficos.setText("Graficos");
        jMOpciones.add(jMIGraficos);

        jMenuBar1.add(jMOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jSPErrores, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
                    .addComponent(jSPEditor, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPErrores, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    public JMenu getjMArchivo() {
        return jMArchivo;
    }

    public void setjMArchivo(JMenu jMArchivo) {
        this.jMArchivo = jMArchivo;
    }

    public JMenuItem getjMIAbrir() {
        return jMIAbrir;
    }

    public void setjMIAbrir(JMenuItem jMIAbrir) {
        this.jMIAbrir = jMIAbrir;
    }

    public JMenuItem getjMIAnalizar() {
        return jMIAnalizar;
    }

    public void setjMIAnalizar(JMenuItem jMIAnalizar) {
        this.jMIAnalizar = jMIAnalizar;
    }

    public JMenuItem getjMIGraficos() {
        return jMIGraficos;
    }

    public void setjMIGraficos(JMenuItem jMIGraficos) {
        this.jMIGraficos = jMIGraficos;
    }

    public JMenuItem getjMIGuardar() {
        return jMIGuardar;
    }

    public void setjMIGuardar(JMenuItem jMIGuardar) {
        this.jMIGuardar = jMIGuardar;
    }

    public JMenuItem getjMIGuardarComo() {
        return jMIGuardarComo;
    }

    public void setjMIGuardarComo(JMenuItem jMIGuardarComo) {
        this.jMIGuardarComo = jMIGuardarComo;
    }

    public JMenuItem getjMINuevo() {
        return jMINuevo;
    }

    public void setjMINuevo(JMenuItem jMINuevo) {
        this.jMINuevo = jMINuevo;
    }

    public JMenu getjMOpciones() {
        return jMOpciones;
    }

    public void setjMOpciones(JMenu jMOpciones) {
        this.jMOpciones = jMOpciones;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JScrollPane getjSPEditor() {
        return jSPEditor;
    }

    public void setjSPEditor(JScrollPane jSPEditor) {
        this.jSPEditor = jSPEditor;
    }

    public JScrollPane getjSPErrores() {
        return jSPErrores;
    }

    public void setjSPErrores(JScrollPane jSPErrores) {
        this.jSPErrores = jSPErrores;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JTextArea getjTAEditor() {
        return jTAEditor;
    }

    public void setjTAEditor(JTextArea jTAEditor) {
        this.jTAEditor = jTAEditor;
    }

    public JTable getjTReporte() {
        return jTReporte;
    }

    public void setjTReporte(JTable jTReporte) {
        this.jTReporte = jTReporte;
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenuItem jMIAbrir;
    private javax.swing.JMenuItem jMIAnalizar;
    private javax.swing.JMenuItem jMIGraficos;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuItem jMIGuardarComo;
    private javax.swing.JMenuItem jMINuevo;
    private javax.swing.JMenu jMOpciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jSPEditor;
    private javax.swing.JScrollPane jSPErrores;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTAEditor;
    private javax.swing.JTable jTReporte;
    // End of variables declaration//GEN-END:variables
}
